# Generated by Django 6.0.6 on 2026-06-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='listenhistory',
            options={'verbose_name': 'История прослушивания', 'verbose_name_plural': 'История прослушиваний'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='playlistmusic',
            options={'verbose_name': 'Музыка в плейлисте', 'verbose_name_plural': 'Музыка в плейлистах'},
        ),
        migrations.AlterModelOptions(
            name='typemusic',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
