# Generated by Django 6.0.3 on 2026-06-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_loginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
