# Generated by Django 6.0.3 on 2026-06-21 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_loginsession_telegram_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_by_admin', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
