services:
  db:
    image: postgres:16
    container_name: music_db
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: full2222
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: music_backend
    ports:
      - "8009:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  bot:
    build: .
    container_name: music_bot
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: python runbot.py

volumes:
  postgres_data: